web:
  build: .
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db:database
db:
  image: library/mysql:5.6.22
  environment:
    MYSQL_ROOT_PASSWORD: abc123
  ports:
    - "3306:3306"
