default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: abc123
  host: db

development:
  <<: *default
  database: wm_training_development

test:
  <<: *default
  database: wm_training_test
